### ISSUE TITLE
meet error in use local embedding model

### ISSUE THREAD

**Issue by sysullf** [TheAiSingularity/graphrag-local-ollama#14]
the error log:
14:35:00,356 httpx INFO HTTP Request: POST http://localhost:11434/api/embeddings "HTTP/1.1 200 OK"
14:35:00,356 httpx INFO HTTP Request: POST http://localhost:11434/api/embeddings "HTTP/1.1 200 OK"
14:35:00,359 graphrag.index.reporting.file_workflow_callbacks INFO Error Invoking LLM details={'input': ['"CHRISTMAS EVE":"Christmas Eve is a significant holiday celebrated by various characters within the text, including Bob Cratchit and others. It\'s a day when the clerk requests time off from work, emphasizing its importance as a festive occasion where no more work is done and shutters are raised. Despite Scrooge\'s initial disapproval of taking time off on Christmas Eve, it serves as a pivotal setting in the narrative, with Scrooge depicted sitting busy in his counting-house before eventually acknowledging the holiday\'s significance."', '"FEZZIWIG":Fezziwig, an old gentleman fondly remembered by Scrooge, is a significant character associated with the warehouse where Scrooge was once apprenticed. Known for his benevolence and jovial nature, Fezziwig commands no more work as night falls on Christmas Eve, initiating a celebration that showcases his leadership and involvement in festivities. He oversees the clearing and preparation of the warehouse to host a domestic ball, demonstrating hospitality and cheer. During this event, Fezziwig dances with Mrs. Fezziwig, adding to the merriment of the occasion. His positive influence on others has earned him gratitude and praise, making him a cherished figure in Scrooge\'s life, evoking feelings of nostalgia and warmth. Through his actions, Fezziwig organizes a dance and social event that not only brings joy but also highlights his role as a leader who actively participates in the celebrations he orchestrates.', '"THE WOMAN":"The Woman" is a complex character who plays a significant role in the unfolding narrative. She appears to be handling the deceased\'s belongings with clear intentions, suggesting she has a purposeful approach to her actions. Her bold personality is evident when she defiantly throws her bundle on the floor and sits down, indicating that she is not easily intimidated by others.\n\nIn one scene, "The Woman" argues passionately about everyone\'s right to take care of themselves, using the deceased\'s past behavior as justification for her current assertiveness. This reveals a strong-willed individual who stands up for what she believes in, even if it means going against societal norms or expectations.\n\nHer involvement in domestic activities is hinted at when she participates in a dialogue about taking down bed-curtains. However, this could also suggest that she might be involved in less savory activities such as theft, adding another layer of intrigue to her character.\n\nIn an interaction with Old Joe, "The Woman" shows a lack of remorse for their actions by laughing at the situation they find themselves in. This callous behavior further highlights her bold and unapologetic nature, making her a compelling figure within the story. Overall, "The Woman" is portrayed as a multi-faceted character with a strong personality, who isn\'t afraid to take what she wants or stand up for her rights.', '"MARLEY":Marley is a central character in Charles Dickens\' "A Christmas Carol," primarily known for being Scrooge\'s deceased business partner. Marley passed away exactly seven years prior on the same night mentioned within the narrative. Despite his death, his presence lingers significantly throughout the story, particularly as his face eerily materializes on a knocker, hinting at supernatural elements that weave through the plot.\n\nMarley\'s demise and burial are pivotal to the beginning of the tale, setting the stage for the ghostly encounters that follow. His death is not only confirmed by Scrooge but also acknowledged widely, solidifying his status as a deceased individual whose impact on Scrooge\'s life remains profound even in death. Marley\'s spectral form appears before Scrooge, influencing his thoughts and actions with an ethereal presence that echoes their past connection.\n\nRemarkably, Marley\'s name still adorns the warehouse door of the firm "Scrooge and Marley," a testament to their once-thriving partnership. This detail underscores the depth of their professional relationship and the lingering influence Marley has over Scrooge\'s life posthumously. The apparition of Marley, with its ghostly features, serves as a haunting reminder of the past, compelling Scrooge to confront his own actions and attitudes.\n\nIn summary, Marley is an essential character in "A Christmas Carol," known for being Scrooge\'s deceased partner whose death, burial, and subsequent appearance as a ghost significantly impact the narrative. His spectral visitation to Scrooge marks a pivotal moment in the story, leading to profound introspection and transformation.', '"STAVE ONE":"Stave One refers to the first section of a narrative, likely detailing Marley\'s death and its aftermath."', '"HAMLET\'S FATHER":"Hamlet\'s father is mentioned as an example to emphasize the certainty of Marley\'s death."', '"MARLEY\'S FUNERAL":', '"SCROOGE AND MARLEY":"Scrooge and Marley is an organization known for its association with both Scrooge and Marley."', '"ST. PAUL\'S CHURCHYARD":"St. Paul\'s Churchyard is a geographical location mentioned as a comparison to the setting of Hamlet\'s father taking a stroll."', '"WEATHER":', '"FOUL WEATHER":', '"BEGGARS":', '"CHILDREN":In this scenario, "CHILDREN" represent two distinct narratives. In one context, the children are shown playing innocently and being cared for by their mother. This scene is set against a backdrop of emotional turmoil as the mother grapples with news related to a man\'s death, suggesting that despite her personal grief, she remains steadfast in providing love and protection to her offspring.\n\nIn another interpretation, "CHILDREN" are portrayed as two figures, specifically a boy and a girl. These children are depicted in a starkly contrasting manner; they are wretched, abject, frightful, hideous, and miserable. This depiction symbolizes the dire consequences of Scrooge\'s actions, highlighting how his behavior has led to their suffering. Here, the children serve as visual representations of the human cost associated with Scrooge\'s selfishness and lack of empathy.\n\nDespite these differing portrayals, both descriptions underscore the vulnerability of children and the profound impact that adult decisions can have on their well-being.', '"BLIND MEN\'S DOGS":', '"THE CITY":"The City refers to a geographical location that serves as the backdrop for the story, characterized by cold, bleak, and foggy weather conditions."', '"CLERK":The Clerk is an employee working under Scrooge at his counting-house, where he spends his days in a small, cell-like room diligently copying letters. He holds a significant position as someone Scrooge wishes to speak to, highlighting their established relationship or connection. On Christmas Eve, the Clerk respectfully requests time off from Scrooge. Despite being an employee, he receives warm Christmas greetings from Scrooge\'s nephew and responds in kind, showcasing a cordial demeanor that extends beyond his professional role.']}
14:35:00,361 graphrag.index.reporting.file_workflow_callbacks INFO Error Invoking LLM details={'input': ['"PROJECT GUTENBERG":"Project Gutenberg is a pioneering organization dedicated to promoting free access to electronic works, commonly known as eBooks. The organization creates, produces, and distributes these electronic books at no cost with minimal restrictions, primarily catering to users in the United States. Project Gutenberg\'s library comprises a vast collection of electronic works, many of which are in the public domain, ensuring that they can be freely shared with anyone. However, it is important to note that there are specific terms and guidelines set by Project Gutenberg for the use and redistribution of these works, which must be complied with to maintain their free distribution status."', '"CHARLES DICKENS":Charles Dickens, a renowned author, is best known for his classic literary work "A Christmas Carol." This iconic novel has been widely recognized and celebrated, also featuring prominently in the Project Gutenberg eBook collection. Through his compelling storytelling, Charles Dickens has left an indelible mark on literature with this cherished tale.', '"ARTHUR RACKHAM":Arthur Rackham, a renowned illustrator, contributed his artistic talents to the 1915 edition of "A Christmas Carol" by Charles Dickens. His illustrations were featured prominently in this publication and later became part of the Project Gutenberg eBook, showcasing Rackham\'s exceptional skill in enhancing literary works with his visual interpretations.', '"SUZANNE SHELL":Suzanne Shell, an integral figure in the literary digitization community, plays a significant role in the production of Project Gutenberg eBooks. Notably, she is among the key producers responsible for bringing to life the digital edition of "A Christmas Carol," showcasing her dedication and expertise in transforming classic literature into accessible eBook formats.', '"JANET BLENKINSHIP":Janet Blenkinship, a notable figure in the digital literature community, played a significant role in the production and creation of eBooks. She was instrumental in contributing to the Project Gutenberg eBook collection, showcasing her dedication to making literature accessible to all. Additionally, Janet\'s expertise extended to producing eBooks, as evidenced by her involvement in creating the digital version of "A Christmas Carol." Her contributions have enriched the world of electronic books, blending her creative skills with a passion for preserving classic literature.', '"J. B. LIPPINCOTT COMPANY":"J. B. Lippincott Company is the publisher of Arthur Rackham\'s illustrated version of \'A Christmas Carol.\'"', '"PHILADELPHIA":"Philadelphia is one of the cities where J. B. Lippincott Company has a presence."', '"NEW YORK":"New York is another city associated with J. B. Lippincott Company\'s operations."', '"A CHRISTMAS CAROL":', '"BOB CRATCHIT":Bob Cratchit, a central character in Charles Dickens\' "A Christmas Carol," serves as Ebenezer Scrooge\'s clerk. He is depicted as a loving and devoted head of the Cratchit family, which includes his wife Mrs. Cratchit and their children, notably Tiny Tim. Despite living in poverty, Bob Cratchit\'s home is filled with resilience and joy, especially during Christmas Eve when he compliments Mrs. Cratchit on her pudding, showing appreciation for her efforts.\n\nBob Cratchit\'s dwelling becomes a significant setting as it is blessed by the Ghost of Christmas Present, highlighting his family\'s warmth amidst their humble circumstances. On Christmas Day, Bob returns home with Tiny Tim, further emphasizing their familial bond and the importance of togetherness during the festive season.\n\nScrooge\'s visit to the Cratchit household marks a pivotal moment in the story, leading to Scrooge\'s decision to raise Bob\'s salary, indicating a significant change in both his working conditions and personal life. This act of generosity by Scrooge also includes plans to send an anonymous gift to Bob, showcasing the transformation in their relationship.\n\nAdditionally, Bob Cratchit is mentioned as having a potential situation for Master Peter that could bring in five-and-sixpence weekly, suggesting he is actively seeking better opportunities for his family\'s welfare. His connection to various locations where Scrooge and the Ghost enter further integrates him into the narrative fabric of "A Christmas Carol."\n\nOverall, Bob Cratchit\'s character embodies the themes of family love, resilience, and hope in the face of adversity, making him a pivotal figure in Dickens\' timeless tale.', '"TIM CRATCHIT":"Tim Cratchit, also known as \'Tiny Tim\', is the youngest son of Bob Cratchit, who is portrayed as a cripple."', '"MR. FEZZIWIG":"Mr. Fezziwig is portrayed as a kind-hearted and jovial old merchant, indicating his significance within the narrative. His warm character suggests that he plays an important role in the story, likely contributing to its heartwarming moments."', '"FRED":Fred, known affectionately by his name in quotes, is prominently recognized as Scrooge\'s nephew, establishing a significant familial bond that potentially holds the key to unfolding the narrative. During a festive gathering, Fred extends an invitation for dinner to his uncle Scrooge, expressing both surprise and warmth upon witnessing Scrooge\'s unexpected appearance at their door. This visit seems to be out of the ordinary, as it catches Fred off guard, indicating that Scrooge\'s presence might not have been anticipated or frequent in the past.\n\nAt one point during the gathering, Fred leads a toast dedicated to his uncle Scrooge\'s health, showcasing a level of respect and affection for him despite any previous estrangement. The atmosphere is filled with an air of mystery as they engage in a guessing game about someone\'s identity, further enriching the dynamics between Fred and Scrooge.\n\nFred also comments on Scrooge\'s notorious belief that Christmas is merely a humbug, suggesting that he might be one of the few who dare to confront or challenge his uncle\'s views. This interaction reveals a boldness in Fred\'s character, as well as an underlying tension or difference in perspective between him and Scrooge.\n\nIn another instance, it is mentioned that Scrooge seeks Fred\'s permission before entering, which could imply either a formality due to the setting being Fred\'s home or a symbolic gesture acknowledging Fred\'s role within their family dynamic. This detail adds depth to their relationship, highlighting respect and boundaries between them despite any previous estrangement.\n\nOverall, Fred emerges as a pivotal character in Scrooge\'s life, bridging gaps through his warmth, hospitality, and willingness to engage with his uncle during the holiday season. His actions and words contribute significantly to the narrative, potentially influencing Scrooge\'s transformation throughout the story.', '"GHOST OF CHRISTMAS PAST":The Ghost of Christmas Past is a significant supernatural entity featured in Charles Dickens\' renowned story \'A Christmas Carol\'. This ethereal being serves as an essential narrative device within the plot. Its primary role involves revealing glimpses of past events to Ebenezer Scrooge, specifically memories from his childhood and earlier life experiences. By doing so, it influences Scrooge\'s current mindset, compelling him to reflect on his past actions and their consequences. The Ghost of Christmas Past is not merely a visual representation but an active participant in the story, guiding Scrooge through a journey of self-discovery and redemption.', '"GHOST OF CHRISTMAS PRESENT":The Ghost of Christmas Present is a supernatural being who embodies the spirit of the current holiday season. This entity has a kind, generous, and hearty nature, which it uses to guide Ebenezer Scrooge through various scenes related to Christmas. The Ghost of Christmas Present shows Scrooge moments that represent both joys and sorrows of the present time, playing a significant role in his transformation. As another spirit visiting Scrooge, this ghost is associated with pivotal experiences during his journey, further enriching his understanding of the true meaning of Christmas.', '"GHOST OF CHRISTMAS YET TO COME":The Ghost of Christmas Yet to Come is a mysterious and supernatural entity that plays a pivotal role in guiding Ebenezer Scrooge through visions of future events. This enigmatic figure presents Scrooge with shadows of things which may potentially happen, offering him a profound glimpse into the possible outcomes of his actions and decisions. By revealing potential futures, the Ghost encourages Scrooge to reflect on his current path and consider the consequences that lie ahead.']}
14:35:00,362 httpx INFO HTTP Request: POST http://localhost:11434/api/embeddings "HTTP/1.1 200 OK"
14:35:00,362 datashaper.workflow.workflow ERROR Error executing verb "text_embed" in create_final_entities: 'NoneType' object is not iterable
Traceback (most recent call last):
  File "E:\miniconda\envs\graphrag\Lib\site-packages\datashaper\workflow\workflow.py", line 415, in _execute_verb
    result = await result
             ^^^^^^^^^^^^
  File "E:\graphrag\graphrag\index\verbs\text\embed\text_embed.py", line 105, in text_embed
    return await _text_embed_in_memory(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\graphrag\graphrag\index\verbs\text\embed\text_embed.py", line 130, in _text_embed_in_memory
    result = await strategy_exec(texts, callbacks, cache, strategy_args)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\graphrag\graphrag\index\verbs\text\embed\strategies\openai.py", line 61, in run
    embeddings = await _execute(llm, text_batches, ticker, semaphore)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\graphrag\graphrag\index\verbs\text\embed\strategies\openai.py", line 105, in _execute
    results = await asyncio.gather(*futures)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\miniconda\envs\graphrag\Lib\asyncio\tasks.py", line 385, in __wakeup
    future.result()
  File "E:\miniconda\envs\graphrag\Lib\asyncio\tasks.py", line 314, in __step_run_and_handle_result
    result = coro.send(None)
             ^^^^^^^^^^^^^^^
  File "E:\graphrag\graphrag\index\verbs\text\embed\strategies\openai.py", line 99, in embed
    chunk_embeddings = await llm(chunk)
                       ^^^^^^^^^^^^^^^^
  File "E:\graphrag\graphrag\llm\base\caching_llm.py", line 104, in __call__
    result = await self._delegate(input, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\graphrag\graphrag\llm\base\rate_limiting_llm.py", line 177, in __call__
    result, start = await execute_with_retry()
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\graphrag\graphrag\llm\base\rate_limiting_llm.py", line 159, in execute_with_retry
    async for attempt in retryer:
  File "E:\miniconda\envs\graphrag\Lib\site-packages\tenacity\asyncio\__init__.py", line 166, in __anext__
    do = await self.iter(retry_state=self._retry_state)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\miniconda\envs\graphrag\Lib\site-packages\tenacity\asyncio\__init__.py", line 153, in iter
    result = await action(retry_state)
             ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\miniconda\envs\graphrag\Lib\site-packages\tenacity\_utils.py", line 99, in inner
    return call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "E:\miniconda\envs\graphrag\Lib\site-packages\tenacity\__init__.py", line 398, in <lambda>
    self._add_action_func(lambda rs: rs.outcome.result())
                                     ^^^^^^^^^^^^^^^^^^^
  File "E:\miniconda\envs\graphrag\Lib\concurrent\futures\_base.py", line 449, in result
    return self.__get_result()
           ^^^^^^^^^^^^^^^^^^^
  File "E:\miniconda\envs\graphrag\Lib\concurrent\futures\_base.py", line 401, in __get_result
    raise self._exception
  File "E:\graphrag\graphrag\llm\base\rate_limiting_llm.py", line 165, in execute_with_retry
    return await do_attempt(), start
           ^^^^^^^^^^^^^^^^^^
  File "E:\graphrag\graphrag\llm\base\rate_limiting_llm.py", line 147, in do_attempt
    return await self._delegate(input, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\graphrag\graphrag\llm\base\base_llm.py", line 49, in __call__
    return await self._invoke(input, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\graphrag\graphrag\llm\base\base_llm.py", line 53, in _invoke
    output = await self._execute_llm(input, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\graphrag\graphrag\llm\openai\openai_embeddings_llm.py", line 36, in _execute_llm
    embedding = await self.client.embeddings.create(
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\miniconda\envs\graphrag\Lib\site-packages\openai\resources\embeddings.py", line 215, in create
    return await self._post(
           ^^^^^^^^^^^^^^^^^
  File "E:\miniconda\envs\graphrag\Lib\site-packages\openai\_base_client.py", line 1826, in post
    return await self.request(cast_to, opts, stream=stream, stream_cls=stream_cls)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\miniconda\envs\graphrag\Lib\site-packages\openai\_base_client.py", line 1519, in request
    return await self._request(
           ^^^^^^^^^^^^^^^^^^^^
  File "E:\miniconda\envs\graphrag\Lib\site-packages\openai\_base_client.py", line 1622, in _request
    return await self._process_response(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\miniconda\envs\graphrag\Lib\site-packages\openai\_base_client.py", line 1714, in _process_response
    return await api_response.parse()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\miniconda\envs\graphrag\Lib\site-packages\openai\_response.py", line 419, in parse
    parsed = self._options.post_parser(parsed)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\miniconda\envs\graphrag\Lib\site-packages\openai\resources\embeddings.py", line 203, in parser
    for embedding in obj.data:
TypeError: 'NoneType' object is not iterable
14:35:00,368 graphrag.index.reporting.file_workflow_callbacks INFO Error executing verb "text_embed" in create_final_entities: 'NoneType' object is not iterable details=None
14:35:00,381 graphrag.index.run ERROR error running workflow create_final_entities
Traceback (most recent call last):
  File "E:\graphrag\graphrag\index\run.py", line 323, in run_pipeline
    result = await workflow.run(context, callbacks)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\miniconda\envs\graphrag\Lib\site-packages\datashaper\workflow\workflow.py", line 369, in run
    timing = await self._execute_verb(node, context, callbacks)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\miniconda\envs\graphrag\Lib\site-packages\datashaper\workflow\workflow.py", line 415, in _execute_verb
    result = await result
             ^^^^^^^^^^^^
  File "E:\graphrag\graphrag\index\verbs\text\embed\text_embed.py", line 105, in text_embed
    return await _text_embed_in_memory(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\graphrag\graphrag\index\verbs\text\embed\text_embed.py", line 130, in _text_embed_in_memory
    result = await strategy_exec(texts, callbacks, cache, strategy_args)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\graphrag\graphrag\index\verbs\text\embed\strategies\openai.py", line 61, in run
    embeddings = await _execute(llm, text_batches, ticker, semaphore)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\graphrag\graphrag\index\verbs\text\embed\strategies\openai.py", line 105, in _execute
    results = await asyncio.gather(*futures)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\miniconda\envs\graphrag\Lib\asyncio\tasks.py", line 385, in __wakeup
    future.result()
  File "E:\miniconda\envs\graphrag\Lib\asyncio\tasks.py", line 314, in __step_run_and_handle_result
    result = coro.send(None)
             ^^^^^^^^^^^^^^^
  File "E:\graphrag\graphrag\index\verbs\text\embed\strategies\openai.py", line 99, in embed
    chunk_embeddings = await llm(chunk)
                       ^^^^^^^^^^^^^^^^
  File "E:\graphrag\graphrag\llm\base\caching_llm.py", line 104, in __call__
    result = await self._delegate(input, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\graphrag\graphrag\llm\base\rate_limiting_llm.py", line 177, in __call__
    result, start = await execute_with_retry()
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\graphrag\graphrag\llm\base\rate_limiting_llm.py", line 159, in execute_with_retry
    async for attempt in retryer:
  File "E:\miniconda\envs\graphrag\Lib\site-packages\tenacity\asyncio\__init__.py", line 166, in __anext__
    do = await self.iter(retry_state=self._retry_state)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\miniconda\envs\graphrag\Lib\site-packages\tenacity\asyncio\__init__.py", line 153, in iter
    result = await action(retry_state)
             ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\miniconda\envs\graphrag\Lib\site-packages\tenacity\_utils.py", line 99, in inner
    return call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "E:\miniconda\envs\graphrag\Lib\site-packages\tenacity\__init__.py", line 398, in <lambda>
    self._add_action_func(lambda rs: rs.outcome.result())
                                     ^^^^^^^^^^^^^^^^^^^
  File "E:\miniconda\envs\graphrag\Lib\concurrent\futures\_base.py", line 449, in result
    return self.__get_result()
           ^^^^^^^^^^^^^^^^^^^
  File "E:\miniconda\envs\graphrag\Lib\concurrent\futures\_base.py", line 401, in __get_result
    raise self._exception
  File "E:\graphrag\graphrag\llm\base\rate_limiting_llm.py", line 165, in execute_with_retry
    return await do_attempt(), start
           ^^^^^^^^^^^^^^^^^^
  File "E:\graphrag\graphrag\llm\base\rate_limiting_llm.py", line 147, in do_attempt
    return await self._delegate(input, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\graphrag\graphrag\llm\base\base_llm.py", line 49, in __call__
    return await self._invoke(input, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\graphrag\graphrag\llm\base\base_llm.py", line 53, in _invoke
    output = await self._execute_llm(input, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\graphrag\graphrag\llm\openai\openai_embeddings_llm.py", line 36, in _execute_llm
    embedding = await self.client.embeddings.create(
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\miniconda\envs\graphrag\Lib\site-packages\openai\resources\embeddings.py", line 215, in create
    return await self._post(
           ^^^^^^^^^^^^^^^^^
  File "E:\miniconda\envs\graphrag\Lib\site-packages\openai\_base_client.py", line 1826, in post
    return await self.request(cast_to, opts, stream=stream, stream_cls=stream_cls)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\miniconda\envs\graphrag\Lib\site-packages\openai\_base_client.py", line 1519, in request
    return await self._request(
           ^^^^^^^^^^^^^^^^^^^^
  File "E:\miniconda\envs\graphrag\Lib\site-packages\openai\_base_client.py", line 1622, in _request
    return await self._process_response(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\miniconda\envs\graphrag\Lib\site-packages\openai\_base_client.py", line 1714, in _process_response
    return await api_response.parse()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\miniconda\envs\graphrag\Lib\site-packages\openai\_response.py", line 419, in parse
    parsed = self._options.post_parser(parsed)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\miniconda\envs\graphrag\Lib\site-packages\openai\resources\embeddings.py", line 203, in parser
    for embedding in obj.data:
TypeError: 'NoneType' object is not iterable
14:35:00,385 graphrag.index.reporting.file_workflow_callbacks INFO Error running pipeline! details=None
14:35:00,406 graphrag.index.reporting.file_workflow_callbacks INFO Error Invoking LLM details={'input': ['"SCROOGE\'S NEPHEW":Scrooge\'s nephew is a central character known for his cheerful and good-natured demeanor. Despite Scrooge\'s often negative attitude and ill whims, he greets his uncle with a warm "A merry Christmas, uncle! God save you!" This greeting reflects the nephew\'s patience, understanding, and desire to reconcile any past conflicts with Scrooge. He is described as someone who enjoys laughing and making merry, finding humor even in Scrooge\'s view of Christmas.\n\nDuring a family gathering or celebration, Scrooge\'s nephew hosts a dinner party where guests engage in lively discussions about young housekeepers while enjoying each other\'s company. The nephew himself participates in games such as blind man\'s buff and Yes and No, showcasing his playful spirit. His hearty laughter surprises Scrooge on occasion, further emphasizing their close familial bond.\n\nThroughout the text, Scrooge\'s nephew is portrayed as a character who comments on an old fellow\'s behavior and wealth, often pleading with his uncle to embrace the true spirit of Christmas. This depiction highlights not only his familial connection but also his role in encouraging Scrooge to reconsider his miserly ways.', '"NEPHEW":Scrooge\'s Nephew, a significant figure in the life of Ebenezer Scrooge, emerges as a central character in the narrative. As the child of someone meaningful to Scrooge, he holds a special place in his uncle\'s history. Despite past conflicts and Scrooge\'s initially cold demeanor towards Christmas, the Nephew extends an olive branch, seeking reconciliation and friendship. His house becomes the destination for Scrooge after a profound change in attitude, symbolizing a new chapter of warmth and familial connection.\n\nThe Nephew is not just a passive figure; he actively challenges Scrooge\'s cynical views on Christmas, advocating for joy and celebration irrespective of financial circumstances. This stance reflects his own resilience and optimism, qualities that ultimately influence Scrooge\'s transformation. Through the Nephew\'s actions and words, Scrooge learns valuable lessons about family, forgiveness, and the true spirit of the holiday season.', '"CHRISTMAS":"CHRISTMAS" holds a significant place in the narrative as it serves as a catalyst for profound change in Scrooge\'s character. Initially viewed negatively by Scrooge, Christmas is contrastingly perceived by his nephew as a time of kindness, forgiveness, charity, and pleasure. It is described as a period when people open their hearts to think kindly of others, bringing about a hopeful promise and festive atmosphere.\n\nDuring the event of Christmas, there\'s an emphasis on toys, presents, and family gatherings, reflecting its central role in the text. This pivotal occasion leads Scrooge to improve Bob Cratchit\'s working conditions and support his family, showcasing the impact of the holiday spirit. Post-transformation, Scrooge learns to celebrate Christmas wholeheartedly, honoring it with a changed heart that now embraces the true essence of the season.', '"CLERK IN THE TANK":"The Clerk in the Tank" is an employee working under Scrooge\'s supervision. Initially, they involuntarily applaud, showcasing a momentary lapse of professional conduct before quickly acknowledging their error. This clerk also seeks time off from Scrooge, further highlighting their subordinate role within the hierarchy. Despite these instances, "The Clerk in the Tank" remains dedicated to their duties under Scrooge\'s management.', '"SCROOGE\'S CLERK":"SCROOGE\'S CLERK", a character of notable mention, finds himself in an economically precarious position as he earns merely fifteen shillings a week. This meager income serves not only him but also supports his wife and family, highlighting the challenging circumstances they face together. The Spirit guides Scrooge to take notice of his clerk\'s situation, emphasizing its significance in the narrative. Through this observation, insights into both the clerk\'s struggle and Scrooge\'s evolving perspective are revealed.', '"PORTLY GENTLEMEN":"The portly gentlemen are described as pleasant to behold and have come to Scrooge\'s office with books and papers, indicating their purposeful visit."', '"GENTLEMAN":"The gentleman, known for his advocacy and compassionate nature, actively engages in promoting welfare for the less fortunate, especially during the festive season. He presents credentials that highlight his commitment to advocating for provision for the poor. In a heartwarming turn of events, this same gentleman receives an unexpected offer of kindness from Scrooge, which leaves him pleasantly surprised and deeply grateful."', '"PRISONS":"Prisons are organizations mentioned to exist in response to Scrooge\'s inquiry."', '"UNION WORKHOUSES":"Union workhouses are organizations that continue to operate, as confirmed by the gentleman."', '"THE GENTLEMAN":"The gentleman is a person who responds to Scrooge\'s inquiries and discusses efforts to raise funds for the poor."', '"TREADMILL":"Treadmill refers to an establishment that is mentioned as being in operation, possibly related to workhouses or prisons."', '"POOR LAW":"Poor Law is a system of laws and regulations concerning the care and support of the poor, which Scrooge confirms is still active."', '"GENTLEMEN":"The gentlemen, a collective of individuals, initially engaged in a discussion with Scrooge but eventually withdrew from it, signaling their disagreement or realization of futility in their point. Despite this interaction, they also represent an organization or group that approaches Scrooge during the holiday season, seeking his charitable contributions."', '"CHURCH":The Church plays a significant role in the narrative, serving not only as a physical location but also as a temporal marker. It is described as having a bell that chimes both the hours and quarters, contributing to the ambiance of the setting and emphasizing its function in delineating time. This church becomes particularly relevant when Scrooge undergoes a transformation in his behavior, leading him to visit it, possibly reflecting a change in his spiritual or moral perspective. The recurring mention of the bell striking hours further underscores the Church\'s symbolic importance in the story, acting as a constant reminder of the passage of time and its implications on Scrooge\'s journey.', '"THE LORD MAYOR":"The Lord Mayor is a person who gives orders for Christmas celebrations at the Mansion House."', '"MANSION HOUSE":"Mansion House refers to the location where the Lord Mayor\'s household celebrates Christmas."']}

it seem the ollama server is ok, but also meet some error in doing embedding.

**Comment by xia-huang-411303** [comment]
good question, I have the same problem but don't know how to solve it

**Comment by sysullf** [comment]
> Good question. I have the same problem but don't know how to solve it. It is recommended that you put the main error in the title, so that more people may see it

hi, i find the error is duel to graphrag use openai sdk not support ollama embedding input, you can follow the [https://github.com/microsoft/graphrag/issues/370](url)  to solve this problem
