### ISSUE TITLE
datashaper.workflow.workflow ERROR Error executing verb "window" in create_final_community_reports: 'community'

### ISSUE THREAD

**Issue by joules457** [TheAiSingularity/graphrag-local-ollama#18]
this error is happening when indexing documents `python -m graphrag.index --root ./ragtest` following the example

This is the complete stack

```
05:07:00,154 datashaper.workflow.workflow INFO executing verb create_community_reports
05:07:26,380 httpx INFO HTTP Request: POST http://127.0.0.1:11434/v1/chat/completions "HTTP/1.1 200 OK"
05:07:46,459 httpx INFO HTTP Request: POST http://127.0.0.1:11434/v1/chat/completions "HTTP/1.1 200 OK"
05:08:06,597 httpx INFO HTTP Request: POST http://127.0.0.1:11434/v1/chat/completions "HTTP/1.1 200 OK"
05:08:26,705 httpx INFO HTTP Request: POST http://127.0.0.1:11434/v1/chat/completions "HTTP/1.1 200 OK"
05:08:26,710 graphrag.index.graph.extractors.community_reports.community_reports_extractor ERROR error generating community report
Traceback (most recent call last):
  File "/workspace/graphrag-local-ollama/graphrag/index/graph/extractors/community_reports/community_reports_extractor.py", line 58, in __call__
    await self._llm(
  File "/workspace/graphrag-local-ollama/graphrag/llm/openai/json_parsing_llm.py", line 34, in __call__
    result = await self._delegate(input, **kwargs)
  File "/workspace/graphrag-local-ollama/graphrag/llm/openai/openai_token_replacing_llm.py", line 37, in __call__
    return await self._delegate(input, **kwargs)
  File "/workspace/graphrag-local-ollama/graphrag/llm/openai/openai_history_tracking_llm.py", line 33, in __call__
    output = await self._delegate(input, **kwargs)
  File "/workspace/graphrag-local-ollama/graphrag/llm/base/caching_llm.py", line 104, in __call__
    result = await self._delegate(input, **kwargs)
  File "/workspace/graphrag-local-ollama/graphrag/llm/base/rate_limiting_llm.py", line 177, in __call__
    result, start = await execute_with_retry()
  File "/workspace/graphrag-local-ollama/graphrag/llm/base/rate_limiting_llm.py", line 159, in execute_with_retry
    async for attempt in retryer:
  File "/usr/local/lib/python3.10/dist-packages/tenacity/asyncio/__init__.py", line 166, in __anext__
    do = await self.iter(retry_state=self._retry_state)
  File "/usr/local/lib/python3.10/dist-packages/tenacity/asyncio/__init__.py", line 153, in iter
    result = await action(retry_state)
  File "/usr/local/lib/python3.10/dist-packages/tenacity/_utils.py", line 99, in inner
    return call(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/tenacity/__init__.py", line 398, in <lambda>
    self._add_action_func(lambda rs: rs.outcome.result())
  File "/usr/lib/python3.10/concurrent/futures/_base.py", line 451, in result
    return self.__get_result()
  File "/usr/lib/python3.10/concurrent/futures/_base.py", line 403, in __get_result
    raise self._exception
  File "/workspace/graphrag-local-ollama/graphrag/llm/base/rate_limiting_llm.py", line 165, in execute_with_retry
    return await do_attempt(), start
  File "/workspace/graphrag-local-ollama/graphrag/llm/base/rate_limiting_llm.py", line 147, in do_attempt
    return await self._delegate(input, **kwargs)
  File "/workspace/graphrag-local-ollama/graphrag/llm/base/base_llm.py", line 48, in __call__
    return await self._invoke_json(input, **kwargs)
  File "/workspace/graphrag-local-ollama/graphrag/llm/openai/openai_chat_llm.py", line 90, in _invoke_json
    raise RuntimeError(FAILED_TO_CREATE_JSON_ERROR)
RuntimeError: Failed to generate valid JSON output
05:08:26,748 graphrag.index.reporting.file_workflow_callbacks INFO Community Report Extraction Error details=None
05:08:26,749 graphrag.index.verbs.graph.report.strategies.graph_intelligence.run_graph_intelligence WARNING No report found for community: 0
05:08:26,826 datashaper.workflow.workflow INFO executing verb window
05:08:26,827 datashaper.workflow.workflow ERROR Error executing verb "window" in create_final_community_reports: 'community'
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/datashaper/workflow/workflow.py", line 410, in _execute_verb
    result = node.verb.func(**verb_args)
  File "/usr/local/lib/python3.10/dist-packages/datashaper/engine/verbs/window.py", line 73, in window
    window = __window_function_map[window_operation](input_table[column])
  File "/usr/local/lib/python3.10/dist-packages/pandas/core/frame.py", line 4102, in __getitem__
    indexer = self.columns.get_loc(key)
  File "/usr/local/lib/python3.10/dist-packages/pandas/core/indexes/range.py", line 417, in get_loc
    raise KeyError(key)
KeyError: 'community'
05:08:26,831 graphrag.index.reporting.file_workflow_callbacks INFO Error executing verb "window" in create_final_community_reports: 'community' details=None
05:08:26,832 graphrag.index.run ERROR error running workflow create_final_community_reports
Traceback (most recent call last):
  File "/workspace/graphrag-local-ollama/graphrag/index/run.py", line 323, in run_pipeline
    result = await workflow.run(context, callbacks)
  File "/usr/local/lib/python3.10/dist-packages/datashaper/workflow/workflow.py", line 369, in run
    timing = await self._execute_verb(node, context, callbacks)
  File "/usr/local/lib/python3.10/dist-packages/datashaper/workflow/workflow.py", line 410, in _execute_verb
    result = node.verb.func(**verb_args)
  File "/usr/local/lib/python3.10/dist-packages/datashaper/engine/verbs/window.py", line 73, in window
    window = __window_function_map[window_operation](input_table[column])
  File "/usr/local/lib/python3.10/dist-packages/pandas/core/frame.py", line 4102, in __getitem__
    indexer = self.columns.get_loc(key)
  File "/usr/local/lib/python3.10/dist-packages/pandas/core/indexes/range.py", line 417, in get_loc
    raise KeyError(key)
KeyError: 'community'
05:08:26,835 graphrag.index.reporting.file_workflow_callbacks INFO Error running pipeline! details=None
```

**Comment by CarolVim** [comment]
i had meet a same error.

**Comment by stephcurt** [comment]
Same issue. I think its due to llama3 prepending "Here is the output in JSON format", trying to trace in the code where I might fix this.

**Comment by stephcurt** [comment]
So I figured out llama3 doesn't really obey grammar rules consistently, but mistral has a json-only output. So I am going to add a json-clean step that uses mistral to clean up llama3's json. Will post if this works.

**Comment by stephcurt** [comment]
Confirmed using mistral to clean llama3s json works.

**Comment by amstrad83** [comment]
Hello there, can you share the solution, i'm pretty new with mistral, and any help will be appreciated
