### ISSUE TITLE
 Errors occurred during the pipeline run, see logs for more details.

### ISSUE THREAD

**Issue by jia95812** [TheAiSingularity/graphrag-local-ollama#30]
执行python -m graphrag.index --root ./ragtest时，发生以下错误：
Traceback (most recent call last):
  File "D:\ProgramData\anaconda3\envs\graphrag-ollama-local\lib\site-packages\datashaper\workflow\workflow.py", line 415, in _execute_verb
    result = await result
  File "E:\graphrag-local-ollama-main\graphrag\index\verbs\text\embed\text_embed.py", line 105, in text_embed
    return await _text_embed_in_memory(
  File "E:\graphrag-local-ollama-main\graphrag\index\verbs\text\embed\text_embed.py", line 130, in _text_embed_in_memory
    result = await strategy_exec(texts, callbacks, cache, strategy_args)
  File "E:\graphrag-local-ollama-main\graphrag\index\verbs\text\embed\strategies\openai.py", line 61, in run
    embeddings = await _execute(llm, text_batches, ticker, semaphore)
  File "E:\graphrag-local-ollama-main\graphrag\index\verbs\text\embed\strategies\openai.py", line 105, in _execute
    results = await asyncio.gather(*futures)
  File "D:\ProgramData\anaconda3\envs\graphrag-ollama-local\lib\asyncio\tasks.py", line 304, in __wakeup
    future.result()
  File "D:\ProgramData\anaconda3\envs\graphrag-ollama-local\lib\asyncio\tasks.py", line 232, in __step
    result = coro.send(None)
  File "E:\graphrag-local-ollama-main\graphrag\index\verbs\text\embed\strategies\openai.py", line 99, in embed
    chunk_embeddings = await llm(chunk)
  File "E:\graphrag-local-ollama-main\graphrag\llm\base\caching_llm.py", line 104, in __call__
    result = await self._delegate(input, **kwargs)
  File "E:\graphrag-local-ollama-main\graphrag\llm\base\rate_limiting_llm.py", line 177, in __call__
    result, start = await execute_with_retry()
  File "E:\graphrag-local-ollama-main\graphrag\llm\base\rate_limiting_llm.py", line 159, in execute_with_retry
    async for attempt in retryer:
  File "D:\ProgramData\anaconda3\envs\graphrag-ollama-local\lib\site-packages\tenacity\asyncio\__init__.py", line 166, in __anext__
    do = await self.iter(retry_state=self._retry_state)
  File "D:\ProgramData\anaconda3\envs\graphrag-ollama-local\lib\site-packages\tenacity\asyncio\__init__.py", line 153, in iter
    result = await action(retry_state)
  File "D:\ProgramData\anaconda3\envs\graphrag-ollama-local\lib\site-packages\tenacity\_utils.py", line 99, in inner
    return call(*args, **kwargs)
  File "D:\ProgramData\anaconda3\envs\graphrag-ollama-local\lib\site-packages\tenacity\__init__.py", line 398, in <lambda>
    self._add_action_func(lambda rs: rs.outcome.result())
  File "D:\ProgramData\anaconda3\envs\graphrag-ollama-local\lib\concurrent\futures\_base.py", line 451, in result
    return self.__get_result()
  File "D:\ProgramData\anaconda3\envs\graphrag-ollama-local\lib\concurrent\futures\_base.py", line 403, in __get_result
    raise self._exception
  File "E:\graphrag-local-ollama-main\graphrag\llm\base\rate_limiting_llm.py", line 165, in execute_with_retry
    return await do_attempt(), start
  File "E:\graphrag-local-ollama-main\graphrag\llm\base\rate_limiting_llm.py", line 147, in do_attempt
    return await self._delegate(input, **kwargs)
  File "E:\graphrag-local-ollama-main\graphrag\llm\base\base_llm.py", line 49, in __call__
    return await self._invoke(input, **kwargs)
  File "E:\graphrag-local-ollama-main\graphrag\llm\base\base_llm.py", line 53, in _invoke
    output = await self._execute_llm(input, **kwargs)
  File "E:\graphrag-local-ollama-main\graphrag\llm\openai\openai_embeddings_llm.py", line 31, in _execute_llm
    embedding = ollama.embeddings(model="nomic-embed-text", prompt=inp)
  File "D:\ProgramData\anaconda3\envs\graphrag-ollama-local\lib\site-packages\ollama\_client.py", line 280, in embeddings
    return self._request(
  File "D:\ProgramData\anaconda3\envs\graphrag-ollama-local\lib\site-packages\ollama\_client.py", line 74, in _request
    raise ResponseError(e.response.text, e.response.status_code) from None
ollama._types.ResponseError
15:00:21,21 graphrag.index.reporting.file_workflow_callbacks INFO Error executing verb "text_embed" in create_final_entities:  details=None
15:00:21,30 graphrag.index.run ERROR error running workflow create_final_entities
Traceback (most recent call last):
  File "E:\graphrag-local-ollama-main\graphrag\index\run.py", line 323, in run_pipeline
    result = await workflow.run(context, callbacks)
  File "D:\ProgramData\anaconda3\envs\graphrag-ollama-local\lib\site-packages\datashaper\workflow\workflow.py", line 369, in run
    timing = await self._execute_verb(node, context, callbacks)
  File "D:\ProgramData\anaconda3\envs\graphrag-ollama-local\lib\site-packages\datashaper\workflow\workflow.py", line 415, in _execute_verb
    result = await result
  File "E:\graphrag-local-ollama-main\graphrag\index\verbs\text\embed\text_embed.py", line 105, in text_embed
    return await _text_embed_in_memory(
  File "E:\graphrag-local-ollama-main\graphrag\index\verbs\text\embed\text_embed.py", line 130, in _text_embed_in_memory
    result = await strategy_exec(texts, callbacks, cache, strategy_args)
  File "E:\graphrag-local-ollama-main\graphrag\index\verbs\text\embed\strategies\openai.py", line 61, in run
    embeddings = await _execute(llm, text_batches, ticker, semaphore)
  File "E:\graphrag-local-ollama-main\graphrag\index\verbs\text\embed\strategies\openai.py", line 105, in _execute
    results = await asyncio.gather(*futures)
  File "D:\ProgramData\anaconda3\envs\graphrag-ollama-local\lib\asyncio\tasks.py", line 304, in __wakeup
    future.result()
  File "D:\ProgramData\anaconda3\envs\graphrag-ollama-local\lib\asyncio\tasks.py", line 232, in __step
    result = coro.send(None)
  File "E:\graphrag-local-ollama-main\graphrag\index\verbs\text\embed\strategies\openai.py", line 99, in embed
    chunk_embeddings = await llm(chunk)
  File "E:\graphrag-local-ollama-main\graphrag\llm\base\caching_llm.py", line 104, in __call__
    result = await self._delegate(input, **kwargs)
  File "E:\graphrag-local-ollama-main\graphrag\llm\base\rate_limiting_llm.py", line 177, in __call__
    result, start = await execute_with_retry()
  File "E:\graphrag-local-ollama-main\graphrag\llm\base\rate_limiting_llm.py", line 159, in execute_with_retry
    async for attempt in retryer:
  File "D:\ProgramData\anaconda3\envs\graphrag-ollama-local\lib\site-packages\tenacity\asyncio\__init__.py", line 166, in __anext__
    do = await self.iter(retry_state=self._retry_state)
  File "D:\ProgramData\anaconda3\envs\graphrag-ollama-local\lib\site-packages\tenacity\asyncio\__init__.py", line 153, in iter
    result = await action(retry_state)
  File "D:\ProgramData\anaconda3\envs\graphrag-ollama-local\lib\site-packages\tenacity\_utils.py", line 99, in inner
    return call(*args, **kwargs)
  File "D:\ProgramData\anaconda3\envs\graphrag-ollama-local\lib\site-packages\tenacity\__init__.py", line 398, in <lambda>
    self._add_action_func(lambda rs: rs.outcome.result())
  File "D:\ProgramData\anaconda3\envs\graphrag-ollama-local\lib\concurrent\futures\_base.py", line 451, in result
    return self.__get_result()
  File "D:\ProgramData\anaconda3\envs\graphrag-ollama-local\lib\concurrent\futures\_base.py", line 403, in __get_result
    raise self._exception
  File "E:\graphrag-local-ollama-main\graphrag\llm\base\rate_limiting_llm.py", line 165, in execute_with_retry
    return await do_attempt(), start
  File "E:\graphrag-local-ollama-main\graphrag\llm\base\rate_limiting_llm.py", line 147, in do_attempt
    return await self._delegate(input, **kwargs)
  File "E:\graphrag-local-ollama-main\graphrag\llm\base\base_llm.py", line 49, in __call__
    return await self._invoke(input, **kwargs)
  File "E:\graphrag-local-ollama-main\graphrag\llm\base\base_llm.py", line 53, in _invoke
    output = await self._execute_llm(input, **kwargs)
  File "E:\graphrag-local-ollama-main\graphrag\llm\openai\openai_embeddings_llm.py", line 31, in _execute_llm
    embedding = ollama.embeddings(model="nomic-embed-text", prompt=inp)
  File "D:\ProgramData\anaconda3\envs\graphrag-ollama-local\lib\site-packages\ollama\_client.py", line 280, in embeddings
    return self._request(
  File "D:\ProgramData\anaconda3\envs\graphrag-ollama-local\lib\site-packages\ollama\_client.py", line 74, in _request
    raise ResponseError(e.response.text, e.response.status_code) from None
ollama._types.ResponseError
15:00:21,31 graphrag.index.reporting.file_workflow_callbacks INFO Error running pipeline! details=None

**Comment by illikea** [comment]
一样的错误，有没有人知道怎么解决

**Comment by jia95812** [comment]
把set OLLAMA_HOST=127.0.0.1，不要用0.0.0.0，就解决了这个问题。

**Comment by Einengutenmorgen** [comment]
Where do i set the Host entry ?

**Comment by jia95812** [comment]
在环境变量里设置
