### ISSUE TITLE
Fails to build knowledge graph.

### ISSUE THREAD

**Issue by dudezilla** [TheAiSingularity/graphrag-local-ollama#76]
tried flailing around with the root directory, in case your domunetation is autogenerated. 

(graphrag-ollama-local) PS C:\Users\spete\grahollama\graphrag-local-ollama\ragtest> python -m graphrag.index --init --root ./
Traceback (most recent call last):
  File "C:\Users\spete\anaconda3\envs\graphrag-ollama-local\lib\runpy.py", line 187, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "C:\Users\spete\anaconda3\envs\graphrag-ollama-local\lib\runpy.py", line 146, in _get_module_details
    return _get_module_details(pkg_main_name, error)
  File "C:\Users\spete\anaconda3\envs\graphrag-ollama-local\lib\runpy.py", line 110, in _get_module_details
    __import__(pkg_name)
  File "C:\Users\spete\grahollama\graphrag-local-ollama\graphrag\index\__init__.py", line 40, in <module>
    from .run import run_pipeline, run_pipeline_with_config
  File "C:\Users\spete\grahollama\graphrag-local-ollama\graphrag\index\run.py", line 59, in <module>
    from .verbs import *  # noqa
  File "C:\Users\spete\grahollama\graphrag-local-ollama\graphrag\index\verbs\__init__.py", line 9, in <module>
    from .graph import (
  File "C:\Users\spete\grahollama\graphrag-local-ollama\graphrag\index\verbs\graph\__init__.py", line 10, in <module>
    from .layout import layout_graph
  File "C:\Users\spete\grahollama\graphrag-local-ollama\graphrag\index\verbs\graph\layout\__init__.py", line 6, in <module>
    from .layout_graph import layout_graph
  File "C:\Users\spete\grahollama\graphrag-local-ollama\graphrag\index\verbs\graph\layout\layout_graph.py", line 13, in <module>
    from graphrag.index.graph.visualization import GraphLayout
  File "C:\Users\spete\grahollama\graphrag-local-ollama\graphrag\index\graph\visualization\__init__.py", line 6, in <module>
    from .compute_umap_positions import compute_umap_positions, get_zero_positions
  File "C:\Users\spete\grahollama\graphrag-local-ollama\graphrag\index\graph\visualization\compute_umap_positions.py", line 6, in <module>
    import graspologic as gc
  File "C:\Users\spete\anaconda3\envs\graphrag-ollama-local\lib\site-packages\graspologic\__init__.py", line 8, in <module>
    import graspologic.inference
  File "C:\Users\spete\anaconda3\envs\graphrag-ollama-local\lib\site-packages\graspologic\inference\__init__.py", line 6, in <module>
    from .latent_distribution_test import latent_distribution_test
  File "C:\Users\spete\anaconda3\envs\graphrag-ollama-local\lib\site-packages\graspologic\inference\latent_distribution_test.py", line 7, in <module>
    from hyppo.ksample import KSample
  File "C:\Users\spete\anaconda3\envs\graphrag-ollama-local\lib\site-packages\hyppo\__init__.py", line 5, in <module>
    import hyppo.kgof
  File "C:\Users\spete\anaconda3\envs\graphrag-ollama-local\lib\site-packages\hyppo\kgof\__init__.py", line 2, in <module>
    from .fssd import FSSD, FSSDH0SimCovObs
  File "C:\Users\spete\anaconda3\envs\graphrag-ollama-local\lib\site-packages\hyppo\kgof\fssd.py", line 4, in <module>
    from past.utils import old_div
ModuleNotFoundError: No module named 'past'

**Comment by Frdoe** [comment]
pip install future solved it for me.

**Comment by dudezilla** [comment]
thanks.
