### ISSUE TITLE
query error

### ISSUE THREAD

**Issue by martain3** [TheAiSingularity/graphrag-local-ollama#82]
root@autodl-container-178642aab5-27ab1567:~/autodl-tmp/graphrag-local-ollama# python -m graphrag.query --root ./ragtest --method global "what is cnn?" 

INFO: Reading settings from ragtest/settings.yaml
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/root/autodl-tmp/graphrag-local-ollama/graphrag/query/__main__.py", line 84, in <module>
    run_global_search(
  File "/root/autodl-tmp/graphrag-local-ollama/graphrag/query/cli.py", line 67, in run_global_search
    final_nodes: pd.DataFrame = pd.read_parquet(
                                ^^^^^^^^^^^^^^^^
  File "/root/miniconda3/lib/python3.12/site-packages/pandas/io/parquet.py", line 667, in read_parquet
    return impl.read(
           ^^^^^^^^^^
  File "/root/miniconda3/lib/python3.12/site-packages/pandas/io/parquet.py", line 267, in read
    path_or_handle, handles, filesystem = _get_path_or_handle(
                                          ^^^^^^^^^^^^^^^^^^^^
  File "/root/miniconda3/lib/python3.12/site-packages/pandas/io/parquet.py", line 140, in _get_path_or_handle
    handles = get_handle(
              ^^^^^^^^^^^
  File "/root/miniconda3/lib/python3.12/site-packages/pandas/io/common.py", line 882, in get_handle
    handle = open(handle, ioargs.mode)
             ^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '/root/autodl-tmp/graphrag-local-ollama/ragtest/output/.ipynb_checkpoints/artifacts/create_final_nodes.parquet'

**Comment by martain3** [comment]
I don't change any path code.why?
